config: {}
dbt_project:
  outputs:
    public:
      dbname: hackathon_pratiksha
      host: dalgo-staging-warehouses.c4hvhyuxrcet.ap-south-1.rds.amazonaws.com
      password: hackathon_pratiksha
      port: 5432
      schema: public
      threads: 4
      type: postgres
      user: hackathon_pratiksha
  target: public
